language: c
compiler:
  - gcc
  - clang
env:
  global:
    - "BUILD_DIR=$TRAVIS_BUILD_DIR"
    - "LD_LIBRARY_PATH=\"$BUILD_DIR/target:$LD_LIBRARY_PATH\""
before_install:
  - "sudo sudo add-apt-repository -y ppa:h-rayflood/gcc-upper"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq gcc doxygen graphviz texlive-latex-base texlive-latex-extra texlive-fonts-extra"
install:
  - "make lib"
script:
  - "nm -D target/libcad.so"
  - "make run-test"
  - "make debuild"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
