language: c
compiler:
  - gcc
  - clang
env:
  global:
    - "BUILD_DIR=$TRAVIS_BUILD_DIR"
    - "LD_LIBRARY_PATH=\"$BUILD_DIR/target:$LD_LIBRARY_PATH\""
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq doxygen graphviz texlive-latex-base texlive-latex-extra texlive-fonts-extra fonts-linuxlibertine fonts-inconsolata devscripts"
install:
  - "make lib"
script:
  - "make run-test"
  - "make debuild"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
