language: c
compiler:
  - gcc
env:
  - "BUILD_DIR=$TRAVIS_BUILD_DIR"
  - "LD_LIBRARY_PATH=\"$BUILD_DIR/target:$LD_LIBRARY_PATH\""
before_install:
  - "sudo apt-get update -qq"
# - "sudo apt-get install -qq doxygen dot"
install:
  - "make lib"
  - "ls -lR target"
  - "ls -lR include"
script:
  - "make run-test"
  - "make debuild"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
