language: c
compiler:
  - gcc
  - clang
env:
  global:
    - "BUILD_DIR=$TRAVIS_BUILD_DIR"
    - "LD_LIBRARY_PATH=\"$BUILD_DIR/target:$LD_LIBRARY_PATH\""
before_install:
  - "sudo sudo add-apt-repository -y ppa:h-rayflood/gcc-upper"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq gcc-4.8 doxygen graphviz texlive-latex-base texlive-latex-extra texlive-fonts-extra"
  - "sudo ln -sf gcc-4.8 /usr/bin/gcc
  - "gcc --version"
install:
  - "make lib"
script:
  - "make run-test"
  - "make debuild"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
