language: c
compiler:
  - gcc
before_install:
  - "sudo apt-get update -qq"
# - "sudo apt-get install -qq doxygen dot"
install:
  - "make lib"
script:
  - "ls -lR target"
  - "make run-test"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
