language: c
compiler:
  - gcc
before_install:
  - "sudo apt-get update -qq"
install:
  - "make release"
script:
  - "ls -l target"
  - "make run-test"
  - "sudo dpkg -i target/dpkg/*.deb"
cache:
  apt: true
